# Generated by Django 5.2.3 on 2025-06-13 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "cedula",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_mascota", models.CharField(max_length=100)),
                ("especie", models.CharField(blank=True, max_length=50)),
                ("raza", models.CharField(blank=True, max_length=50)),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to="principal.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("motivo", models.TextField(blank=True)),
                ("diagnostico", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="principal.mascota",
                    ),
                ),
            ],
        ),
    ]
