# Generated by Django 5.2.3 on 2025-06-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_med", models.CharField(max_length=100)),
                ("presentacion", models.CharField(max_length=100)),
                ("stock_disponible", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_prof", models.CharField(max_length=100)),
                ("tarjeta_profesional", models.CharField(max_length=50, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="consulta",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="req_cirugia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="consulta",
            name="req_medicamentos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tratamiento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.CharField(default=9999999, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="FormulaMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosis", models.CharField(max_length=100)),
                ("frecuencia", models.CharField(max_length=100)),
                ("duracion", models.CharField(max_length=100)),
                ("via_administracion", models.CharField(max_length=100)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="principal.consulta",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="principal.medicamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cirugia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedimiento", models.CharField(max_length=255)),
                ("descripcion_proced", models.TextField(blank=True, null=True)),
                ("fecha_prog", models.DateField()),
                ("hora_prog", models.TimeField()),
                ("duracion_aprox", models.DurationField()),
                ("estado", models.CharField(max_length=100)),
                ("observaciones_cirugia", models.TextField(blank=True, null=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cirugias",
                        to="principal.mascota",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cirugias",
                        to="principal.profesional",
                    ),
                ),
            ],
        ),
    ]
