# Generated by Django 5.2.3 on 2025-06-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0002_medicamento_profesional_consulta_observaciones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="med_entregado",
            field=models.BooleanField(default=False),
        ),
    ]
