# Generated by Django 5.2.3 on 2025-06-24 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_consulta_med_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cirugia', to='principal.consulta'),
        ),
    ]
